### ISSUE TITLE
Test suits encoding problems

### ISSUE THREAD

**Issue by scalder27** [karma-runner/karma-teamcity-reporter#32]
Hello, I`ve encountered a teamcity reporter output issue with russian symbols in the test suits.
This issue can be reproduced by adding next test (*karma-teamcity-reporter\examples\simple\index.spec.js*):
```javascript
it('это тоже должно работать', function () {
    1 + 1 === 2
})
````

And there is a screenshot from the teamcity:
![image](https://cloud.githubusercontent.com/assets/4444106/9730838/9da4402c-5632-11e5-908c-376a66e91d7c.png)

**Comment by thojo** [comment]
+1

I have the same problem with german umlauts. When not using the teamcity reporter umlauts are correctly displayed in build logs.

**Comment by dizel3d** [comment]
The bug is produced by fix d8d9e70630031de66036d81b396561fb6de20f70 (issue #5): Windows OS console use ANSI and `fs.writeSync` cannot print language-specific symbols correctly.
Issue #5 occurred because `process.stdout.write` was non-blocking in node up to v0.11.11. But since **node v0.11.12 (2014.03.11)** it is blocking. See [nodejs v0.11.12 (2014.03.11) changelog](https://github.com/nodejs/node-v0.x-archive/blob/v0.11.12/ChangeLog): *windows: make stdout/sterr pipes blocking (Alexis Campailla)*. I check this, and you can [check this too](https://github.com/dizel3d/node-stdout-pipe-test).
I think we can revert d8d9e70630031de66036d81b396561fb6de20f70 to fix the bug and add to readme *Supported nodejs version: >= v0.11.12 for Windows, >= v0.10.x for Linux*.

**Comment by dizel3d** [comment]
I am sorry, I was wrong in previous comment. It does not fix the bug, it just fixes encoding in console. I thought that TeamCity emulates TTY.

**Comment by dizel3d** [comment]
Ok, guys, take the solution! You should add configuration parameter `teamcity.runner.commandline.stdstreams.encoding` with value `UTF8`.
![image](https://cloud.githubusercontent.com/assets/593571/14072546/438d9ac0-f4ca-11e5-8670-7e549ff3be27.png)
Thanks to the topics:
http://stackoverflow.com/questions/9213241/teamcity-build-log/29716411#29716411
https://youtrack.jetbrains.com/issue/TW-4177#comment=27-1038539

**Comment by scalder27** [comment]
@dizel3d, it's unbelievable! You did an amazing investigation! Thank you very much!
